# investment_report.py
"""
Generate Investment Report for Client
"""

import pandas as pd
import json
from datetime import datetime

class InvestmentReport:
    """Generate investment reports from dashboard data"""
    
    @staticmethod
    def generate_summary(df: pd.DataFrame) -> dict:
        """Generate summary insights"""
        top_picks = df.nlargest(3, 'Investment_Score')
        
        report = {
            'date': datetime.now().strftime('%d %b %Y'),
            'top_picks': top_picks[['Company Name', 'Investment_Score', 'Recommendation', 'Risk_Level']].to_dict('records'),
            'market_sentiment': {
                'strong_buy': len(df[df['Recommendation'] == 'Strong Buy']),
                'buy': len(df[df['Recommendation'] == 'Buy']),
                'hold': len(df[df['Recommendation'] == 'Hold']),
                'sell': len(df[df['Recommendation'] == 'Sell']),
                'strong_sell': len(df[df['Recommendation'] == 'Strong Sell'])
            },
            'sector_health': {
                'avg_growth': df['Revenue_Growth'].mean(),
                'avg_margin': df['Net_Margin'].mean(),
                'avg_score': df['Investment_Score'].mean()
            }
        }
        return report
    
    @staticmethod
    def to_json(report: dict, filename: str = None):
        """Save report as JSON"""
        if not filename:
            filename = f"investment_report_{datetime.now().strftime('%Y%m%d')}.json"
        
        with open(filename, 'w') as f:
            json.dump(report, f, indent=2)
        
        return filename
    
    @staticmethod
    def to_markdown(report: dict) -> str:
        """Generate markdown report for client"""
        md = f"""
# NIFTY IT Investment Report - {report['date']}

## Top Picks

| Company | Score | Recommendation | Risk Level |
|---------|-------|----------------|------------|
"""
        for pick in report['top_picks']:
            md += f"| {pick['Company Name']} | {pick['Investment_Score']:.2f} | {pick['Recommendation']} | {pick['Risk_Level']} |\n"
        
        md += f"""

## Market Sentiment

- Strong Buy: {report['market_sentiment']['strong_buy']}
- Buy: {report['market_sentiment']['buy']}
- Hold: {report['market_sentiment']['hold']}
- Sell: {report['market_sentiment']['sell']}
- Strong Sell: {report['market_sentiment']['strong_sell']}

## Sector Health

- Average Growth: {report['sector_health']['avg_growth']:.1f}%
- Average Margin: {report['sector_health']['avg_margin']:.1f}%
- Average Score: {report['sector_health']['avg_score']:.2f}/5.0

---
*Generated by NIFTY IT Investment Dashboard*
"""
        return md